sudo: required
services:
  - docker

script:
  - docker build -t elk .
  - docker images
  - docker run --name elk -d -p 9200:9200 -p 5601:5601 -p 5044:5044 elk
  - docker ps -a
  - sleep 60  
  - docker logs elk | grep elasticsearch
  - docker logs elk | grep logstash
  - docker logs elk | grep kibana  
  - docker exec -it elk ps -ef
  - echo "Checking Elasticsearch"
  - curl http://localhost:9200/_nodes/process?pretty
  - echo "Checking Kibana"
  - curl http://localhost:5601/

