sudo: required
services:
  - docker

script:
  - docker build -t elk .
  - docker run --name elk -d elk
  - docker ps -a
  # - docker logs -f elk
  - sleep 20
  - docker exec -it elk ps -ef
  - docker exec -it elk curl http://localhost:9200/_nodes/process?pretty

