version: "3"
services:
  elasticsearch:
    # image: elasticsearch:latest
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.0
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - docker_elk
  logstash:
    # image: logstash:latest
    image: docker.elastic.co/logstash/logstash:5.3.0
    ports:
      - "5044:5044"
    # links:
      # - elasticsearch
    networks:
      - docker_elk
  kibana:
    # image: kibana:latest
    image: docker.elastic.co/kibana/kibana:5.3.0
    ports:
      - "5601:5601"
    # links:
      # - elasticsearch
    networks:
      - docker_elk
networks:
  docker_elk:
    driver: bridge